// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConnectMetamaskWalletController from "./connect_metamask_wallet_controller"
application.register("connect-metamask-wallet", ConnectMetamaskWalletController)
